package com.example.plantdetector.utils

object Constants {
    const val INPUT_SIZE = 256
    const val CONFIDENCE_THRESHOLD = 0.25f

    // ترتیب دقیقاً مطابق خروجی مدل TFLite (تأییدشده با کالیبراسیون)
    val CLASS_NAMES = listOf(
        "Acinos_graveolens",  // 0
        "Agrimonia_eupatoria",  // 1
        "Ajuga_chamaecistus",  // 2
        "Allium_atroviolaceum",  // 3
        "Allium_hirtifolium",  // 4
        "Allium_longisepalum",  // 5
        "Allium_scabriscapum",  // 6
        "Allium_vineale",  // 7
        "Amygdalus_arabica",  // 8
        "Amygdalus_communis",  // 9
        "Amygdalus_lycioides",  // 10
        "Amygdalus_orientalis",  // 11
        "Armeniaca_vulgaris",  // 12
        "Astragalus_albispinus",  // 13
        "Astragalus_angustiflorus",  // 14
        "Astragalus_argyrostachys",  // 15
        "Astragalus_asterias",  // 16
        "Astragalus_campylanthus",  // 17
        "Astragalus_campylorhynchus",  // 18
        "Astragalus_caragana",  // 19
        "Astragalus_cephalanthus",  // 20
        "Astragalus_cyclophyllon",  // 21
        "Astragalus_ebenoides",  // 22
        "Astragalus_effesus",  // 23
        "Astragalus_fasciculifolius",  // 24
        "Astragalus_fragiferus",  // 25
        "Astragalus_gossypinus",  // 26
        "Astragalus_hamosus",  // 27
        "Astragalus_ibicinus",  // 28
        "Astragalus_kirrindicus",  // 29
        "Astragalus_macrocephalus",  // 30
        "Astragalus_macroplematus",  // 31
        "Astragalus_microcephalus",  // 32
        "Astragalus_oleifolius",  // 33
        "Astragalus_ovinus",  // 34
        "Astragalus_oxyglottis",  // 35
        "Astragalus_podolobus",  // 36
        "Astragalus_rhodosemius",  // 37
        "Astragalus_sp",  // 38
        "Astragalus_teheranicus",  // 39
        "Astragalus_verus",  // 40
        "Bellevalia_macrobotrys",  // 41
        "Cerasus_avium",  // 42
        "Cerasus_mahaleb",  // 43
        "Cerasus_microcarpa",  // 44
        "Cerasus_vulgaris",  // 45
        "Colchicum_kotschyi",  // 46
        "Coronilla_varia",  // 47
        "Crataegus_persica",  // 48
        "Crataegus_pseudoheterophylla",  // 49
        "Eremostachys_macrophylla",  // 50
        "Eremurus_inderiensis",  // 51
        "Eremurus_persicus",  // 52
        "Eremurus_spectabilis",  // 53
        "Fritillaria_gibbosa",  // 54
        "Fritillaria_imperialis",  // 55
        "Fritillaria_persica",  // 56
        "Glycyrrhiza_glabra",  // 57
        "Lallemantia_iberica",  // 58
        "Lallemantia_peltata",  // 59
        "Lamium_album",  // 60
        "Lamium_amplexicaule",  // 61
        "Lathyrus_aphaca",  // 62
        "Lathyrus_cassius",  // 63
        "Lathyrus_inconspicuus",  // 64
        "Lens_orientalis",  // 65
        "Lotus_corniculatus",  // 66
        "Malus_domestica",  // 67
        "Marrubium_astracanicum",  // 68
        "Marrubium_cuneatum",  // 69
        "Marrubium_vulgare",  // 70
        "Medicago_coronata",  // 71
        "Medicago_lupulina",  // 72
        "Medicago_minima",  // 73
        "Medicago_polymorpha",  // 74
        "Medicago_radiata",  // 75
        "Medicago_rigidula",  // 76
        "Medicago_sativa",  // 77
        "Medicago_scutellata",  // 78
        "Melilotus_albus",  // 79
        "Melilotus_indicus",  // 80
        "Melilotus_officinalis",  // 81
        "Mentha_longifolia",  // 82
        "Micromeria_myrtifolia",  // 83
        "Muscari_inconstrictum",  // 84
        "Muscari_neglectum",  // 85
        "Nectaroscordum_tripedale",  // 86
        "Nepeta_glomerulosa_carmanica",  // 87
        "Onobrychis_cornuta",  // 88
        "Onobrychis_crista-galli",  // 89
        "Onobrychis_melanotricha",  // 90
        "Ononis_reclinata",  // 91
        "Ononis_spinosa",  // 92
        "Ornithogalum_arcuatum",  // 93
        "Ornithogalum_narbonense",  // 94
        "Ornithogalum_orthophyllum",  // 95
        "Ornithogalum_recurvum",  // 96
        "Persica_vulgaris",  // 97
        "Phlomis_olivieri",  // 98
        "Phlomis_persica",  // 99
        "Pisum_sativum",  // 100
        "Potentilla_reptans",  // 101
        "Potentilla_speciosa",  // 102
        "Prunus_domestica",  // 103
        "Pyracantha_coccinea",  // 104
        "Pyrus_communis",  // 105
        "Pyrus_elaeagnifolia",  // 106
        "Pyrus_syriaca",  // 107
        "Rosa_canina",  // 108
        "Rosa_foetida",  // 109
        "Rosa_orientalis",  // 110
        "Salvia_ceratophylla",  // 111
        "Salvia_hydrangea",  // 112
        "Salvia_multicaulis",  // 113
        "Salvia_nemorosa",  // 114
        "Salvia_palaestina",  // 115
        "Salvia_sclarea",  // 116
        "Salvia_syriaca",  // 117
        "Salvia_virgata",  // 118
        "Sanguisorba_minor",  // 119
        "Scorpiurus_muricatus",  // 120
        "Sophora_alopecuroides",  // 121
        "Sorbus_persica",  // 122
        "Spartium_junceum",  // 123
        "Stachys_inflata",  // 124
        "Stachys_lavandulifolia",  // 125
        "Stachys_spectabilis",  // 126
        "Teucrium_orientale",  // 127
        "Teucrium_polium",  // 128
        "Teucrium_scordium",  // 129
        "Trifolium_campestre",  // 130
        "Trifolium_pratense",  // 131
        "Trifolium_purpureum",  // 132
        "Trifolium_repens",  // 133
        "Trifolium_resupinatum",  // 134
        "Trifolium_tomentosum",  // 135
        "Trigonella_Spruneriana",  // 136
        "Trigonella_caerulescens",  // 137
        "Trigonella_monantha",  // 138
        "Trigonella_stellata",  // 139
        "Tulipa_biebersteiniana",  // 140
        "Tulipa_biflora",  // 141
        "Tulipa_systola",  // 142
        "Vicia_amphicarpa",  // 143
        "Vicia_narbonensis",  // 144
        "Vicia_peregrina",  // 145
        "Vicia_variabilis",  // 146
        "Vicia_villosa",  // 147
        "Ziziphora_capitata",  // 148
        "Ziziphora_clinopodioides",  // 149
        "Ziziphora_tenuior"  // 150
    )
}
