package com.example.plantdetector.utils

object Constants {
    // ⚙️ تنظیمات مدل
    const val INPUT_SIZE = 224          // اندازه ورودی مدل (باید با آموزش مطابقت داشته باشد)
    const val CONFIDENCE_THRESHOLD = 0.25f  // آستانه اطمینان تشخیص
    
    // ⚠️ مهم: ترتیب این لیست باید دقیقاً مطابق با ترتیب کلاس‌ها در مدل باشد
    // پس از آماده شدن مدل نهایی، با اسکریپت extract_classes.py بررسی می‌شود
    val CLASS_NAMES = listOf(
        // ═══════════════════════════════════════════════════════
        // خانواده Fabaceae (باقلائیان) - ۶۹ گونه
        // ═══════════════════════════════════════════════════════
        "Astragalus_albispinus",
        "Astragalus_angustiflorus",
        "Astragalus_argyrostachys",
        "Astragalus_asterias",
        "Astragalus_campylanthus",
        "Astragalus_campylorhynchus",
        "Astragalus_caragana",
        "Astragalus_cephalanthus",
        "Astragalus_cyclophyllon",
        "Astragalus_ebenoides",
        "Astragalus_effesus",
        "Astragalus_fasciculifolius",
        "Astragalus_fragiferus",
        "Astragalus_gossypinus",
        "Astragalus_hamosus",
        "Astragalus_ibicinus",
        "Astragalus_kirrindicus",
        "Astragalus_macrocephalus",
        "Astragalus_macroplematus",
        "Astragalus_microcephalus",
        "Astragalus_oleifolius",
        "Astragalus_ovinus",
        "Astragalus_oxyglottis",
        "Astragalus_podolobus",
        "Astragalus_rhodosemius",
        "Astragalus_sp",
        "Astragalus_teheranicus",
        "Astragalus_verus",
        "Coronilla_varia",
        "Glycyrrhiza_glabra",
        "Lathyrus_aphaca",
        "Lathyrus_cassius",
        "Lathyrus_inconspicuus",
        "Lens_orientalis",
        "Lotus_corniculatus",
        "Medicago_coronata",
        "Medicago_lupulina",
        "Medicago_minima",
        "Medicago_polymorpha",
        "Medicago_radiata",
        "Medicago_rigidula",
        "Medicago_sativa",
        "Medicago_scutellata",
        "Melilotus_albus",
        "Melilotus_indicus",
        "Melilotus_officinalis",
        "Onobrychis_cornuta",
        "Onobrychis_crista-galli",
        "Onobrychis_melanotricha",
        "Ononis_reclinata",
        "Ononis_spinosa",
        "Pisum_sativum",
        "Scorpiurus_muricatus",
        "Sophora_alopecuroides",
        "Trifolium_campestre",
        "Trifolium_pratense",
        "Trifolium_purpureum",
        "Trifolium_repens",
        "Trifolium_resupinatum",
        "Trifolium_tomentosum",
        "Trigonella_caerulescens",
        "Trigonella_monantha",
        "Trigonella_Spruneriana",
        "Trigonella_stellata",
        "Vicia_amphicarpa",
        "Vicia_narbonensis",
        "Vicia_peregrina",
        "Vicia_variabilis",
        "Vicia_villosa",
        
        // ═══════════════════════════════════════════════════════
        // خانواده Lamiaceae (نعنائیان) - ۳۲ گونه
        // ═══════════════════════════════════════════════════════
        "Acinos_graveolens",
        "Ajuga_chamaecistus",
        "Eremostachys_macrophylla",
        "Lallemantia_iberica",
        "Lallemantia_peltata",
        "Lamium_album",
        "Lamium_amplexicaule",
        "Marrubium_astracanicum",
        "Marrubium_cuneatum",
        "Marrubium_vulgare",
        "Mentha_longifolia",
        "Micromeria_myrtifolia",
        "Nepeta_glomerulosa_carmanica",
        "Phlomis_olivieri",
        "Phlomis_persica",
        "Salvia_ceratophylla",
        "Salvia_hydrangea",
        "Salvia_multicaulis",
        "Salvia_nemorosa",
        "Salvia_palaestina",
        "Salvia_sclarea",
        "Salvia_syriaca",
        "Salvia_virgata",
        "Stachys_inflata",
        "Stachys_lavandulifolia",
        "Stachys_spectabilis",
        "Teucrium_orientale",
        "Teucrium_polium",
        "Teucrium_scordium",
        "Ziziphora_capitata",
        "Ziziphora_clinopodioides",
        "Ziziphora_tenuior",
        
        // ═══════════════════════════════════════════════════════
        // خانواده Liliaceae (سوسنیان) - ۲۳ گونه
        // ═══════════════════════════════════════════════════════
        "Allium_atroviolaceum",
        "Allium_hirtifolium",
        "Allium_longisepalum",
        "Allium_scabriscapum",
        "Allium_vineale",
        "Bellevalia_macrobotrys",
        "Colchicum_kotschyi",
        "Eremurus_inderiensis",
        "Eremurus_persicus",
        "Eremurus_spectabilis",
        "Fritillaria_gibbosa",
        "Fritillaria_imperialis",
        "Fritillaria_persica",
        "Muscari_inconstrictum",
        "Muscari_neglectum",
        "Nectaroscordum_tripedale",
        "Ornithogalum_arcuatum",
        "Ornithogalum_narbonense",
        "Ornithogalum_orthophyllum",
        "Ornithogalum_recurvum",
        "Tulipa_biebersteiniana",
        "Tulipa_biflora",
        "Tulipa_systola",
        
        // ═══════════════════════════════════════════════════════
        // خانواده Rosaceae (گل‌سرخیان) - ۲۷ گونه
        // ═══════════════════════════════════════════════════════
        "Agrimonia_eupatoria",
        "Amygdalus_arabica",
        "Amygdalus_communis",
        "Amygdalus_lycioides",
        "Amygdalus_orientalis",
        "Armeniaca_vulgaris",
        "Cerasus_avium",
        "Cerasus_mahaleb",
        "Cerasus_microcarpa",
        "Cerasus_vulgaris",
        "Crataegus_persica",
        "Crataegus_pseudoheterophylla",
        "Malus_domestica",
        "Persica_vulgaris",
        "Potentilla_reptans",
        "Potentilla_speciosa",
        "Prunus_domestica",
        "Pyracantha_coccinea",
        "Pyrus_communis",
        "Pyrus_elaeagnifolia",
        "Pyrus_syriaca",
        "Rosa_canina",
        "Rosa_foetida",
        "Rosa_orientalis",
        "Sanguisorba_minor",
        "Sorbus_persica",
        "Spartium_junceum"
    )
}
